version: '2.2'

services:
    explorer-frontend:
        image: "nginx:stable"
        restart: always
        container_name: explorer-frontend
        volumes:
        - "./configs/nginx-explorer-frontend.conf:/etc/nginx/conf.d/default.conf:ro"
        - "./data/karbo-blockchain-explorer:/usr/share/nginx/html:ro"
        ports:
        - "80:80"
        - "443:443"
        depends_on:
        - explorer-php-fpm
        networks:
        - explorer-network
    
    explorer-php-fpm:
        image: "php:7-fpm"
        restart: always
        container_name: explorer-php-fpm
        expose:
            - "9000"
        networks:
        - explorer-network
        
networks:
    explorer-network:
        driver: bridge